version: "3.8"

services:
  web:
    build:
      context: .
    container_name: flask-service
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
      FLASK_APP: app.py
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_USER: root
      DATABASE_PASSWORD: example
      DATABASE_NAME: flaskdb
    depends_on:
      - db
    volumes:
      - ./app:/app

  db:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: flaskdb
      MYSQL_USER: flaskuser
      MYSQL_PASSWORD: flaskpassword
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
