services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: node:16
    restart: on-failure
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=example
      - DB_NAME=app_db
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: app_db
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
